use yew::Properties;

#[derive(Clone, PartialEq)]
pub struct Image {
    pub src: String,
    pub loading: String,
}

#[derive(Properties, PartialEq)]
pub struct ImageListProps {
    pub images: Vec<Image>,
}

pub fn get_images() -> Vec<Image> {
    let images = vec![
        // Image { src: "gallery/00234.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/00355.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/00483.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/00964.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/01288.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/01318.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/01378.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/01394.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/02086.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/02161.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/02974.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/03411.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/03554.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/03591.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/03652.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/04179.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/04202.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/04631.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/05225.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/05587.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/05737.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/06392.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/07281.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/07348.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/08033.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/08643.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/08876.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/08914.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/09178.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/09200.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/09305.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/09381.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/09976.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/10585.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/11067.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/11188.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/11293.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/11496.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/11782.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/11880.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/12678.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/13649.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/14658.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/15019.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/15193.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/15238.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/15840.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/16081.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/16202.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/16924.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/17029.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/17308.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/17940.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/19288.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/19424.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/19491.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/19551.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/19687.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/20229.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/20448.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/20816.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/21118.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/21177.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/21200.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/21645.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/22443.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/23000.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/23542.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/23978.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/24438.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/24633.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/24768.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/25100.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/25265.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/25273.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/25762.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/25905.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/27110.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/27773.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28172.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28186.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28187.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28510.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28781.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28962.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/28999.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/29067.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/29346.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/29662.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/29955.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/30746.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/30844.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/30904.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/31108.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/31401.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/31559.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/32192.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/32590.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/33140.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/33539.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/33870.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/34329.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/36295.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/36588.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/37559.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/37627.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/37860.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/37928.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/38327.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/38410.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/38899.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/39396.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/39682.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/39697.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/39923.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/40096.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/40428.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/40608.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/40684.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/41684.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/42377.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/43130.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/43778.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/43928.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44018.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44078.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44184.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44192.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44365.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44546.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/44561.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/45366.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/46171.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/46555.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/46571.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/46826.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/48031.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/49213.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/49386.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/50071.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/50305.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/51358.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/51758.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/52300.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/52428.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/52819.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/53143.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/53278.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/53640.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/53752.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/53881.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/53963.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/54257.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/54528.jpg".to_string(), loading: "lazy".to_string() },
        // Image { src: "gallery/54965.jpg".to_string(), loading: "lazy".to_string() },
        Image { src: "gallery/55258.jpg".to_string(), loading: "lazy".to_string() },
        Image { src: "gallery/55461.jpg".to_string(), loading: "lazy".to_string() },
        Image { src: "gallery/56515.jpg".to_string(), loading: "lazy".to_string() },
        Image { src: "gallery/57366.jpg".to_string(), loading: "lazy".to_string() },
        Image { src: "gallery/58254.jpg".to_string(), loading: "lazy".to_string() },
    ];
    images
}